services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"


  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  user-db:
    image: postgres:13-alpine
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=user_service_password
    volumes:
      - user_postgres_data:/var/lib/postgresql/data/


  group-db:
    image: postgres:13-alpine
    container_name: group-db
    ports:
      - "5433:5432" 
    environment:
      - POSTGRES_DB=group_service_db
      - POSTGRES_USER=group_service_user
      - POSTGRES_PASSWORD=group_service_password
    volumes:
      - group_postgres_data:/var/lib/postgresql/data/

  goal-db:
    image: postgres:13-alpine
    container_name: goal-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=goal_service_db
      - POSTGRES_USER=goal_service_user
      - POSTGRES_PASSWORD=goal_service_password
    volumes:
      - goal_postgres_data:/var/lib/postgresql/data/


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    depends_on:
      - kafka
      - user-db
    environment:
      - DJANGO_SETTINGS_MODULE=user_service.settings
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=user_service_password
      - DB_HOST=user-db
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


  group-service:
    build: ./group-service
    container_name: group-service
    ports:
      - "8002:8000"
    depends_on:
      - kafka
      - group-db
    environment:
      - DJANGO_SETTINGS_MODULE=group_service.settings
      - POSTGRES_DB=group_service_db
      - POSTGRES_USER=group_service_user
      - POSTGRES_PASSWORD=group_service_password
      - DB_HOST=group-db
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


  goal-service:
    build: ./goal-service
    container_name: goal-service
    ports:
      - "8003:8000"
    depends_on:
      - kafka
      - goal-db
    environment:
      - DJANGO_SETTINGS_MODULE=goal_service.settings
      - POSTGRES_DB=goal_service_db
      - POSTGRES_USER=goal_service_user
      - POSTGRES_PASSWORD=goal_service_password
      - DB_HOST=goal-db
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


volumes:
  user_postgres_data:
  group_postgres_data:
  goal_postgres_data:
