version: '3.9'

services:
  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  # Databases
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB_USER}
      - POSTGRES_USER=${POSTGRES_USER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_USER}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data/

  group-db:
    image: postgres:15-alpine
    container_name: group-db
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB_GROUP}
      - POSTGRES_USER=${POSTGRES_USER_GROUP}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_GROUP}
    volumes:
      - group_postgres_data:/var/lib/postgresql/data/

  goal-db:
    image: postgres:15-alpine
    container_name: goal-db
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB_GOAL}
      - POSTGRES_USER=${POSTGRES_USER_GOAL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_GOAL}
    volumes:
      - goal_postgres_data:/var/lib/postgresql/data/

  # Microservices
  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - kafka
      - user-db
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
      - ./user-service/.env

  group-service:
    build: ./group-service
    container_name: group-service
    depends_on:
      - kafka
      - group-db
    ports:
      - "8002:8000"
    env_file:
      - .env.dev
      - ./group-service/.env

  goal-service:
    build: ./goal-service
    container_name: goal-service
    depends_on:
      - kafka
      - goal-db
    ports:
      - "8003:8000"
    env_file:
      - .env.dev
      - ./goal-service/.env

volumes:
  user_postgres_data:
  group_postgres_data:
  goal_postgres_data:
