services: 
  user-service: 
    build: ./order-service
    container_name: order-service
    ports:
      - "8001:8000"
    db:
     image: postgres-15
    ENVIRONMENT:
        - POSTGRES_NAME = 
        - POSTGRES_USER = postgres
        - POSTGRES_PASSWORD = postgres  
        

   